image: "python:3.7"

# Do before script
before_script:
  - python --version
  - pip install -r requirements.txt

# Different stages
stages:
  - Static Analysis

# Linting
flake8:
  stage: Static Analysis
  script:
  - flake8 --max-line-length=120 bild/*.py
  tags:
    - flake8TriggerPR
  only:
    - tags