image: "python:3.7"

# Do before script
before_script:
  - python --version
  - pip3 install -r docker/flask/requirements.txt

# Different stages
stages:
  - Static Analysis
  - Test

# Linting
flake8:
  allow_failure: true
  stage: Static Analysis
  script:
  - flake8 --max-line-length=120 app/*.py

# Unit tests
pytest:
  stage: Test
  script:
  - pwd
  - ls -l
  - export PYTHONPATH="$PYTHONPATH:."
  - python -c "import sys;print(sys.path)"
  - pytest

# Trigger build