image: docker:latest

variables:
  DOCKER_DRIVER: overlay

services:
- docker:dind

before_script:
- docker info
- apk update
- apk upgrade
- apk add python3 python-dev py-pip build-base
- pip3 install docker-compose

build:
  stage: build
  script:
  - docker-compose -f docker-compose.test.yml build
