version: '3'

services:

  web:
    build:
        context: ./
        dockerfile: ./docker/flask/Dockerfile
        args:
            PORT: ${PORT}
            TYPE: ${TYPE}
    ports:
        - "5000:5000"
    depends_on:
        - mysql
    volumes:
        - "./app:/var/www/flask/app"

  redis:
    image: "redis:alpine"