version: '3'

services:

  web:
    restart: always
    container_name: web_${FLASK_SERVER_TYPE}_${DATA_NUMBER}
    build:
        context: ./
        dockerfile: ./docker/flask/Dockerfile
        args:
            FLASK_PORT: ${FLASK_PORT}
            FLASK_SERVER_TYPE: ${FLASK_SERVER_TYPE}
            FLASK_DEBUG: ${FLASK_DEBUG}
    ports:
        - "${FLASK_PORT}:${FLASK_PORT}"
    depends_on:
        - mysql
    volumes:
        - "./app:/var/www/flask/app"
    command: sh -c "/wait && python3 run.py"
    environment:
        - WAIT_HOSTS=mysql:3306
        - WAIT_HOSTS_TIMEOUT=50
        - WAIT_SLEEP_INTERVAL=1
        - WAIT_HOST_CONNECT_TIMEOUT=1

  redis:
    container_name: redis_${FLASK_SERVER_TYPE}_${DATA_NUMBER}
    image: "redis:alpine"

#Starts the mysql server
  mysql:
    # TO be implemented later
    build: ./docker/mysql/8.0
    restart: always
    container_name: mysql_${FLASK_SERVER_TYPE}_${DATA_NUMBER}
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: '${MYSQL_DATABASE_USER}'
      # You can use whatever password you like
      MYSQL_PASSWORD: '${MYSQL_DATABASE_PASSWORD}'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '${MYSQL_DATABASE_PASSWORD}'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '${MYSQL_PORT}:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306"]
      interval: 3s
      timeout: 1s
      retries: 30

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_${FLASK_SERVER_TYPE}_${DATA_NUMBER}
    restart: always
    # Gives the phpmyadmin container access to the mysql container
    links:
      - mysql
    environment:
      # Links the mysql database hosted on port 3306 inside the container to phpmyadmin
      PMA_HOST: mysql
      PMA_PORT: 3306
    restart: always
    # Acccessible on port 55102 on host
    ports:
      - ${PHPMYADMIN_PORT}:80
    volumes:
      - /sessions
