version: '3'

services:

#Starts the nginx server and python 3.6
  web:
    # will build ./docker/web/Dockerfile
    build: ./docker/web
    restart: always
    ports:
      - "56733:80"
    volumes:
      - /app:/var/www
    #volumes:
      #- type: volume
        #source: app
        #target: /data
        #volume:
          #nocopy: true
      #- type: bind
        #source: ./static
        #target: /opt/app/static


#Starts the mysql server    
  db:
    build: ./docker/db
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:
