version: '3'

services:

  #Starts the apache server and python 3.6
  apache:
    # will build ./docker/web/Dockerfile
    container_name: apache_${FLASK_SERVER_TYPE}
    build: 
      context: ./
      dockerfile: ./docker/apache/Dockerfile
      args:
        FLASK_SERVER_TYPE: ${FLASK_SERVER_TYPE}
    restart: always
    depends_on:
      - mysql
    links:
      - phpmyadmin
    ports:
      - "${FLASK_PORT}:80"
