CREATE TABLE IF NOT EXISTS servers (
  id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) NOT NULL,
  address VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
  username VARCHAR(255) PRIMARY KEY NOT NULL,
  server_id INTEGER NOT NULL,
  FOREIGN KEY (server_id) REFERENCES servers(id),
  creation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_edit_date TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  last_ping_date TIMESTAMP DEFAULT NULL
);