CREATE TABLE IF NOT EXISTS users (
    username VARCHAR(1000) NOT NULL,
    address VARCHAR(1000) NOT NULL,
    creation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_edit_date TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    last_ping_date TIMESTAMP DEFAULT NULL
);

