CREATE TABLE IF NOT EXISTS users (
    username VARCHAR(255) PRIMARY KEY NOT NULL,
    address VARCHAR(1000) NOT NULL,
    server INT NULL,
    creation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_edit_date TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    last_ping_date TIMESTAMP DEFAULT NULL
    );

CREATE TABLE IF NOT EXISTS servers (
  id INT PRIMARY KEY NOT NULL,
  name VARCHAR(45) NOT NULL,
  address VARCHAR(45) NOT NULL
  );