CREATE TABLE IF NOT EXISTS posts (
    rowid INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    body VARCHAR(1000) NOT NULL,
    title VARCHAR(1000) DEFAULT NULL,
    profile_id INTEGER NOT NULL,
    creation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

--CREATE TABLE IF NOT EXISTS friends (
--    rowid INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
--    profile_id INTEGER NOT NULL,
--    friend VARCHAR(1000) NOT NULL,
--    creation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
--);

--CREATE TABLE IF NOT EXISTS profiles (
--    rowid INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
--    username VARCHAR(1000) NOT NULL,
--    name VARCHAR(1000) NOT NULL,
--    image_location VARCHAR(1000) DEFAULT NULL,
--    location VARCHAR(1000) DEFAULT NULL,
--    study VARCHAR(1000) DEFAULT NULL,
--    creation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--    last_edit_date TIMESTAMP DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
--);

