CREATE TABLE IF NOT EXISTS users (
    username VARCHAR NOT NULL,
    address VARCHAR NOT NULL,
    creation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_edit_date TIMESTAMP DEFAULT 0,
    last_ping_date TIMESTAMP DEFAULT 0
);

