CREATE TABLE IF NOT EXISTS posts (
    body VARCHAR NOT NULL,
    title VARCHAR DEFAULT 0,
    profile_id INTEGER NOT NULL,
    creation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS friends (
    profile_id INTEGER NOT NULL,
    friend VARCHAR NOT NULL,
    creation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS profiles (
    username VARCHAR NOT NULL,
    name VARCHAR NOT NULL,
    image_location VARCHAR DEFAULT 0,
    location VARCHAR DEFAULT 0,
    study VARCHAR DEFAULT 0,
    creation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

